### ISSUE TITLE
What is the meaning of label(1, 2) ? 

### ISSUE THREAD

**Issue by bemoregt** [gongyanc/kddcup99#1]
Hi, @gongyanc 

What is the meaning of label(1, 2) ? 

Normal/ Malware ??

Thanks.

**Comment by gongyanc** [comment]
Mentioned In line 29

class_label.append(item_mat[-1]) # 表格中最后一列正常1异常2的分类存入class_label

1:Normal

2:Malware

I should change 2(Malware) to -1

Thank you!

________________________________
发件人: Gromit Park <notifications@github.com>
发送时间: 2017年6月2日 16:44:34
收件人: gongyanc/kddcup99
抄送: 龚焱; Mention
主题: [gongyanc/kddcup99] What is the meaning of label(1, 2) ? (#1)


Hi, @gongyanc<https://github.com/gongyanc>

What is the meaning of label(1, 2) ?

Normal/ Malware ??

Thanks.

―

**Comment by bemoregt** [comment]
Thank you, @gongyanc 

In your ROC Curve,
How can I calculate the AUC area percentage?

Many Thanks
